version: "3.3"

services:
  postgres:
    image: postgres:15.4
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "manga"

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - backend
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "password"

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - backend
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=manga
      
networks:
  backend:

volumes:
  minio_data:
    driver: local
