// Code generated by ent, DO NOT EDIT.

package progress

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/wutipong/mangaweb3-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Progress {
	return predicate.Progress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Progress {
	return predicate.Progress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Progress {
	return predicate.Progress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Progress {
	return predicate.Progress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Progress {
	return predicate.Progress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Progress {
	return predicate.Progress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Progress {
	return predicate.Progress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Progress {
	return predicate.Progress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Progress {
	return predicate.Progress(sql.FieldLTE(FieldID, id))
}

// Page applies equality check predicate on the "page" field. It's identical to PageEQ.
func Page(v int) predicate.Progress {
	return predicate.Progress(sql.FieldEQ(FieldPage, v))
}

// PageEQ applies the EQ predicate on the "page" field.
func PageEQ(v int) predicate.Progress {
	return predicate.Progress(sql.FieldEQ(FieldPage, v))
}

// PageNEQ applies the NEQ predicate on the "page" field.
func PageNEQ(v int) predicate.Progress {
	return predicate.Progress(sql.FieldNEQ(FieldPage, v))
}

// PageIn applies the In predicate on the "page" field.
func PageIn(vs ...int) predicate.Progress {
	return predicate.Progress(sql.FieldIn(FieldPage, vs...))
}

// PageNotIn applies the NotIn predicate on the "page" field.
func PageNotIn(vs ...int) predicate.Progress {
	return predicate.Progress(sql.FieldNotIn(FieldPage, vs...))
}

// PageGT applies the GT predicate on the "page" field.
func PageGT(v int) predicate.Progress {
	return predicate.Progress(sql.FieldGT(FieldPage, v))
}

// PageGTE applies the GTE predicate on the "page" field.
func PageGTE(v int) predicate.Progress {
	return predicate.Progress(sql.FieldGTE(FieldPage, v))
}

// PageLT applies the LT predicate on the "page" field.
func PageLT(v int) predicate.Progress {
	return predicate.Progress(sql.FieldLT(FieldPage, v))
}

// PageLTE applies the LTE predicate on the "page" field.
func PageLTE(v int) predicate.Progress {
	return predicate.Progress(sql.FieldLTE(FieldPage, v))
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.Progress {
	return predicate.Progress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Meta) predicate.Progress {
	return predicate.Progress(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Progress {
	return predicate.Progress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Progress {
	return predicate.Progress(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Progress) predicate.Progress {
	return predicate.Progress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Progress) predicate.Progress {
	return predicate.Progress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Progress) predicate.Progress {
	return predicate.Progress(sql.NotPredicates(p))
}
