// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MetaColumns holds the columns for the "meta" table.
	MetaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "favorite", Type: field.TypeBool, Default: false},
		{Name: "file_indices", Type: field.TypeJSON},
		{Name: "thumbnail", Type: field.TypeBytes, Nullable: true},
		{Name: "read", Type: field.TypeBool},
	}
	// MetaTable holds the schema information for the "meta" table.
	MetaTable = &schema.Table{
		Name:       "meta",
		Columns:    MetaColumns,
		PrimaryKey: []*schema.Column{MetaColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "favorite", Type: field.TypeBool, Default: false},
		{Name: "hidden", Type: field.TypeBool, Default: false},
		{Name: "thumbnail", Type: field.TypeBytes, Nullable: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// TagMetaColumns holds the columns for the "tag_meta" table.
	TagMetaColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt},
		{Name: "meta_id", Type: field.TypeInt},
	}
	// TagMetaTable holds the schema information for the "tag_meta" table.
	TagMetaTable = &schema.Table{
		Name:       "tag_meta",
		Columns:    TagMetaColumns,
		PrimaryKey: []*schema.Column{TagMetaColumns[0], TagMetaColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_meta_tag_id",
				Columns:    []*schema.Column{TagMetaColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_meta_meta_id",
				Columns:    []*schema.Column{TagMetaColumns[1]},
				RefColumns: []*schema.Column{MetaColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MetaTable,
		TagsTable,
		TagMetaTable,
	}
)

func init() {
	TagMetaTable.ForeignKeys[0].RefTable = TagsTable
	TagMetaTable.ForeignKeys[1].RefTable = MetaTable
}
