// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/wutipong/mangaweb3-backend/ent/history"
	"github.com/wutipong/mangaweb3-backend/ent/meta"
	"github.com/wutipong/mangaweb3-backend/ent/predicate"
	"github.com/wutipong/mangaweb3-backend/ent/progress"
	"github.com/wutipong/mangaweb3-backend/ent/tag"
	"github.com/wutipong/mangaweb3-backend/ent/user"
)

// MetaUpdate is the builder for updating Meta entities.
type MetaUpdate struct {
	config
	hooks    []Hook
	mutation *MetaMutation
}

// Where appends a list predicates to the MetaUpdate builder.
func (mu *MetaUpdate) Where(ps ...predicate.Meta) *MetaUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetName sets the "name" field.
func (mu *MetaUpdate) SetName(s string) *MetaUpdate {
	mu.mutation.SetName(s)
	return mu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableName(s *string) *MetaUpdate {
	if s != nil {
		mu.SetName(*s)
	}
	return mu
}

// SetCreateTime sets the "create_time" field.
func (mu *MetaUpdate) SetCreateTime(t time.Time) *MetaUpdate {
	mu.mutation.SetCreateTime(t)
	return mu
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableCreateTime(t *time.Time) *MetaUpdate {
	if t != nil {
		mu.SetCreateTime(*t)
	}
	return mu
}

// SetFavorite sets the "favorite" field.
func (mu *MetaUpdate) SetFavorite(b bool) *MetaUpdate {
	mu.mutation.SetFavorite(b)
	return mu
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableFavorite(b *bool) *MetaUpdate {
	if b != nil {
		mu.SetFavorite(*b)
	}
	return mu
}

// SetFileIndices sets the "file_indices" field.
func (mu *MetaUpdate) SetFileIndices(i []int) *MetaUpdate {
	mu.mutation.SetFileIndices(i)
	return mu
}

// AppendFileIndices appends i to the "file_indices" field.
func (mu *MetaUpdate) AppendFileIndices(i []int) *MetaUpdate {
	mu.mutation.AppendFileIndices(i)
	return mu
}

// SetRead sets the "read" field.
func (mu *MetaUpdate) SetRead(b bool) *MetaUpdate {
	mu.mutation.SetRead(b)
	return mu
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableRead(b *bool) *MetaUpdate {
	if b != nil {
		mu.SetRead(*b)
	}
	return mu
}

// SetActive sets the "active" field.
func (mu *MetaUpdate) SetActive(b bool) *MetaUpdate {
	mu.mutation.SetActive(b)
	return mu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableActive(b *bool) *MetaUpdate {
	if b != nil {
		mu.SetActive(*b)
	}
	return mu
}

// SetHidden sets the "hidden" field.
func (mu *MetaUpdate) SetHidden(b bool) *MetaUpdate {
	mu.mutation.SetHidden(b)
	return mu
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableHidden(b *bool) *MetaUpdate {
	if b != nil {
		mu.SetHidden(*b)
	}
	return mu
}

// SetContainerType sets the "container_type" field.
func (mu *MetaUpdate) SetContainerType(mt meta.ContainerType) *MetaUpdate {
	mu.mutation.SetContainerType(mt)
	return mu
}

// SetNillableContainerType sets the "container_type" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableContainerType(mt *meta.ContainerType) *MetaUpdate {
	if mt != nil {
		mu.SetContainerType(*mt)
	}
	return mu
}

// SetThumbnailIndex sets the "thumbnail_index" field.
func (mu *MetaUpdate) SetThumbnailIndex(i int) *MetaUpdate {
	mu.mutation.ResetThumbnailIndex()
	mu.mutation.SetThumbnailIndex(i)
	return mu
}

// SetNillableThumbnailIndex sets the "thumbnail_index" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableThumbnailIndex(i *int) *MetaUpdate {
	if i != nil {
		mu.SetThumbnailIndex(*i)
	}
	return mu
}

// AddThumbnailIndex adds i to the "thumbnail_index" field.
func (mu *MetaUpdate) AddThumbnailIndex(i int) *MetaUpdate {
	mu.mutation.AddThumbnailIndex(i)
	return mu
}

// ClearThumbnailIndex clears the value of the "thumbnail_index" field.
func (mu *MetaUpdate) ClearThumbnailIndex() *MetaUpdate {
	mu.mutation.ClearThumbnailIndex()
	return mu
}

// SetThumbnailX sets the "thumbnail_x" field.
func (mu *MetaUpdate) SetThumbnailX(i int) *MetaUpdate {
	mu.mutation.ResetThumbnailX()
	mu.mutation.SetThumbnailX(i)
	return mu
}

// SetNillableThumbnailX sets the "thumbnail_x" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableThumbnailX(i *int) *MetaUpdate {
	if i != nil {
		mu.SetThumbnailX(*i)
	}
	return mu
}

// AddThumbnailX adds i to the "thumbnail_x" field.
func (mu *MetaUpdate) AddThumbnailX(i int) *MetaUpdate {
	mu.mutation.AddThumbnailX(i)
	return mu
}

// ClearThumbnailX clears the value of the "thumbnail_x" field.
func (mu *MetaUpdate) ClearThumbnailX() *MetaUpdate {
	mu.mutation.ClearThumbnailX()
	return mu
}

// SetThumbnailY sets the "thumbnail_y" field.
func (mu *MetaUpdate) SetThumbnailY(i int) *MetaUpdate {
	mu.mutation.ResetThumbnailY()
	mu.mutation.SetThumbnailY(i)
	return mu
}

// SetNillableThumbnailY sets the "thumbnail_y" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableThumbnailY(i *int) *MetaUpdate {
	if i != nil {
		mu.SetThumbnailY(*i)
	}
	return mu
}

// AddThumbnailY adds i to the "thumbnail_y" field.
func (mu *MetaUpdate) AddThumbnailY(i int) *MetaUpdate {
	mu.mutation.AddThumbnailY(i)
	return mu
}

// ClearThumbnailY clears the value of the "thumbnail_y" field.
func (mu *MetaUpdate) ClearThumbnailY() *MetaUpdate {
	mu.mutation.ClearThumbnailY()
	return mu
}

// SetThumbnailWidth sets the "thumbnail_width" field.
func (mu *MetaUpdate) SetThumbnailWidth(i int) *MetaUpdate {
	mu.mutation.ResetThumbnailWidth()
	mu.mutation.SetThumbnailWidth(i)
	return mu
}

// SetNillableThumbnailWidth sets the "thumbnail_width" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableThumbnailWidth(i *int) *MetaUpdate {
	if i != nil {
		mu.SetThumbnailWidth(*i)
	}
	return mu
}

// AddThumbnailWidth adds i to the "thumbnail_width" field.
func (mu *MetaUpdate) AddThumbnailWidth(i int) *MetaUpdate {
	mu.mutation.AddThumbnailWidth(i)
	return mu
}

// ClearThumbnailWidth clears the value of the "thumbnail_width" field.
func (mu *MetaUpdate) ClearThumbnailWidth() *MetaUpdate {
	mu.mutation.ClearThumbnailWidth()
	return mu
}

// SetThumbnailHeight sets the "thumbnail_height" field.
func (mu *MetaUpdate) SetThumbnailHeight(i int) *MetaUpdate {
	mu.mutation.ResetThumbnailHeight()
	mu.mutation.SetThumbnailHeight(i)
	return mu
}

// SetNillableThumbnailHeight sets the "thumbnail_height" field if the given value is not nil.
func (mu *MetaUpdate) SetNillableThumbnailHeight(i *int) *MetaUpdate {
	if i != nil {
		mu.SetThumbnailHeight(*i)
	}
	return mu
}

// AddThumbnailHeight adds i to the "thumbnail_height" field.
func (mu *MetaUpdate) AddThumbnailHeight(i int) *MetaUpdate {
	mu.mutation.AddThumbnailHeight(i)
	return mu
}

// ClearThumbnailHeight clears the value of the "thumbnail_height" field.
func (mu *MetaUpdate) ClearThumbnailHeight() *MetaUpdate {
	mu.mutation.ClearThumbnailHeight()
	return mu
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (mu *MetaUpdate) AddTagIDs(ids ...int) *MetaUpdate {
	mu.mutation.AddTagIDs(ids...)
	return mu
}

// AddTags adds the "tags" edges to the Tag entity.
func (mu *MetaUpdate) AddTags(t ...*Tag) *MetaUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return mu.AddTagIDs(ids...)
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (mu *MetaUpdate) AddHistoryIDs(ids ...int) *MetaUpdate {
	mu.mutation.AddHistoryIDs(ids...)
	return mu
}

// AddHistories adds the "histories" edges to the History entity.
func (mu *MetaUpdate) AddHistories(h ...*History) *MetaUpdate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return mu.AddHistoryIDs(ids...)
}

// AddFavoriteOfUserIDs adds the "favorite_of_user" edge to the User entity by IDs.
func (mu *MetaUpdate) AddFavoriteOfUserIDs(ids ...int) *MetaUpdate {
	mu.mutation.AddFavoriteOfUserIDs(ids...)
	return mu
}

// AddFavoriteOfUser adds the "favorite_of_user" edges to the User entity.
func (mu *MetaUpdate) AddFavoriteOfUser(u ...*User) *MetaUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return mu.AddFavoriteOfUserIDs(ids...)
}

// AddProgresIDs adds the "progress" edge to the Progress entity by IDs.
func (mu *MetaUpdate) AddProgresIDs(ids ...int) *MetaUpdate {
	mu.mutation.AddProgresIDs(ids...)
	return mu
}

// AddProgress adds the "progress" edges to the Progress entity.
func (mu *MetaUpdate) AddProgress(p ...*Progress) *MetaUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mu.AddProgresIDs(ids...)
}

// Mutation returns the MetaMutation object of the builder.
func (mu *MetaUpdate) Mutation() *MetaMutation {
	return mu.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (mu *MetaUpdate) ClearTags() *MetaUpdate {
	mu.mutation.ClearTags()
	return mu
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (mu *MetaUpdate) RemoveTagIDs(ids ...int) *MetaUpdate {
	mu.mutation.RemoveTagIDs(ids...)
	return mu
}

// RemoveTags removes "tags" edges to Tag entities.
func (mu *MetaUpdate) RemoveTags(t ...*Tag) *MetaUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return mu.RemoveTagIDs(ids...)
}

// ClearHistories clears all "histories" edges to the History entity.
func (mu *MetaUpdate) ClearHistories() *MetaUpdate {
	mu.mutation.ClearHistories()
	return mu
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (mu *MetaUpdate) RemoveHistoryIDs(ids ...int) *MetaUpdate {
	mu.mutation.RemoveHistoryIDs(ids...)
	return mu
}

// RemoveHistories removes "histories" edges to History entities.
func (mu *MetaUpdate) RemoveHistories(h ...*History) *MetaUpdate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return mu.RemoveHistoryIDs(ids...)
}

// ClearFavoriteOfUser clears all "favorite_of_user" edges to the User entity.
func (mu *MetaUpdate) ClearFavoriteOfUser() *MetaUpdate {
	mu.mutation.ClearFavoriteOfUser()
	return mu
}

// RemoveFavoriteOfUserIDs removes the "favorite_of_user" edge to User entities by IDs.
func (mu *MetaUpdate) RemoveFavoriteOfUserIDs(ids ...int) *MetaUpdate {
	mu.mutation.RemoveFavoriteOfUserIDs(ids...)
	return mu
}

// RemoveFavoriteOfUser removes "favorite_of_user" edges to User entities.
func (mu *MetaUpdate) RemoveFavoriteOfUser(u ...*User) *MetaUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return mu.RemoveFavoriteOfUserIDs(ids...)
}

// ClearProgress clears all "progress" edges to the Progress entity.
func (mu *MetaUpdate) ClearProgress() *MetaUpdate {
	mu.mutation.ClearProgress()
	return mu
}

// RemoveProgresIDs removes the "progress" edge to Progress entities by IDs.
func (mu *MetaUpdate) RemoveProgresIDs(ids ...int) *MetaUpdate {
	mu.mutation.RemoveProgresIDs(ids...)
	return mu
}

// RemoveProgress removes "progress" edges to Progress entities.
func (mu *MetaUpdate) RemoveProgress(p ...*Progress) *MetaUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mu.RemoveProgresIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MetaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MetaUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MetaUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MetaUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MetaUpdate) check() error {
	if v, ok := mu.mutation.Name(); ok {
		if err := meta.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Meta.name": %w`, err)}
		}
	}
	if v, ok := mu.mutation.ContainerType(); ok {
		if err := meta.ContainerTypeValidator(v); err != nil {
			return &ValidationError{Name: "container_type", err: fmt.Errorf(`ent: validator failed for field "Meta.container_type": %w`, err)}
		}
	}
	return nil
}

func (mu *MetaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(meta.Table, meta.Columns, sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Name(); ok {
		_spec.SetField(meta.FieldName, field.TypeString, value)
	}
	if value, ok := mu.mutation.CreateTime(); ok {
		_spec.SetField(meta.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := mu.mutation.Favorite(); ok {
		_spec.SetField(meta.FieldFavorite, field.TypeBool, value)
	}
	if value, ok := mu.mutation.FileIndices(); ok {
		_spec.SetField(meta.FieldFileIndices, field.TypeJSON, value)
	}
	if value, ok := mu.mutation.AppendedFileIndices(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, meta.FieldFileIndices, value)
		})
	}
	if value, ok := mu.mutation.Read(); ok {
		_spec.SetField(meta.FieldRead, field.TypeBool, value)
	}
	if value, ok := mu.mutation.Active(); ok {
		_spec.SetField(meta.FieldActive, field.TypeBool, value)
	}
	if value, ok := mu.mutation.Hidden(); ok {
		_spec.SetField(meta.FieldHidden, field.TypeBool, value)
	}
	if value, ok := mu.mutation.ContainerType(); ok {
		_spec.SetField(meta.FieldContainerType, field.TypeEnum, value)
	}
	if value, ok := mu.mutation.ThumbnailIndex(); ok {
		_spec.SetField(meta.FieldThumbnailIndex, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedThumbnailIndex(); ok {
		_spec.AddField(meta.FieldThumbnailIndex, field.TypeInt, value)
	}
	if mu.mutation.ThumbnailIndexCleared() {
		_spec.ClearField(meta.FieldThumbnailIndex, field.TypeInt)
	}
	if value, ok := mu.mutation.ThumbnailX(); ok {
		_spec.SetField(meta.FieldThumbnailX, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedThumbnailX(); ok {
		_spec.AddField(meta.FieldThumbnailX, field.TypeInt, value)
	}
	if mu.mutation.ThumbnailXCleared() {
		_spec.ClearField(meta.FieldThumbnailX, field.TypeInt)
	}
	if value, ok := mu.mutation.ThumbnailY(); ok {
		_spec.SetField(meta.FieldThumbnailY, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedThumbnailY(); ok {
		_spec.AddField(meta.FieldThumbnailY, field.TypeInt, value)
	}
	if mu.mutation.ThumbnailYCleared() {
		_spec.ClearField(meta.FieldThumbnailY, field.TypeInt)
	}
	if value, ok := mu.mutation.ThumbnailWidth(); ok {
		_spec.SetField(meta.FieldThumbnailWidth, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedThumbnailWidth(); ok {
		_spec.AddField(meta.FieldThumbnailWidth, field.TypeInt, value)
	}
	if mu.mutation.ThumbnailWidthCleared() {
		_spec.ClearField(meta.FieldThumbnailWidth, field.TypeInt)
	}
	if value, ok := mu.mutation.ThumbnailHeight(); ok {
		_spec.SetField(meta.FieldThumbnailHeight, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedThumbnailHeight(); ok {
		_spec.AddField(meta.FieldThumbnailHeight, field.TypeInt, value)
	}
	if mu.mutation.ThumbnailHeightCleared() {
		_spec.ClearField(meta.FieldThumbnailHeight, field.TypeInt)
	}
	if mu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedTagsIDs(); len(nodes) > 0 && !mu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !mu.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedFavoriteOfUserIDs(); len(nodes) > 0 && !mu.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.FavoriteOfUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedProgressIDs(); len(nodes) > 0 && !mu.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{meta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MetaUpdateOne is the builder for updating a single Meta entity.
type MetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MetaMutation
}

// SetName sets the "name" field.
func (muo *MetaUpdateOne) SetName(s string) *MetaUpdateOne {
	muo.mutation.SetName(s)
	return muo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableName(s *string) *MetaUpdateOne {
	if s != nil {
		muo.SetName(*s)
	}
	return muo
}

// SetCreateTime sets the "create_time" field.
func (muo *MetaUpdateOne) SetCreateTime(t time.Time) *MetaUpdateOne {
	muo.mutation.SetCreateTime(t)
	return muo
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableCreateTime(t *time.Time) *MetaUpdateOne {
	if t != nil {
		muo.SetCreateTime(*t)
	}
	return muo
}

// SetFavorite sets the "favorite" field.
func (muo *MetaUpdateOne) SetFavorite(b bool) *MetaUpdateOne {
	muo.mutation.SetFavorite(b)
	return muo
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableFavorite(b *bool) *MetaUpdateOne {
	if b != nil {
		muo.SetFavorite(*b)
	}
	return muo
}

// SetFileIndices sets the "file_indices" field.
func (muo *MetaUpdateOne) SetFileIndices(i []int) *MetaUpdateOne {
	muo.mutation.SetFileIndices(i)
	return muo
}

// AppendFileIndices appends i to the "file_indices" field.
func (muo *MetaUpdateOne) AppendFileIndices(i []int) *MetaUpdateOne {
	muo.mutation.AppendFileIndices(i)
	return muo
}

// SetRead sets the "read" field.
func (muo *MetaUpdateOne) SetRead(b bool) *MetaUpdateOne {
	muo.mutation.SetRead(b)
	return muo
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableRead(b *bool) *MetaUpdateOne {
	if b != nil {
		muo.SetRead(*b)
	}
	return muo
}

// SetActive sets the "active" field.
func (muo *MetaUpdateOne) SetActive(b bool) *MetaUpdateOne {
	muo.mutation.SetActive(b)
	return muo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableActive(b *bool) *MetaUpdateOne {
	if b != nil {
		muo.SetActive(*b)
	}
	return muo
}

// SetHidden sets the "hidden" field.
func (muo *MetaUpdateOne) SetHidden(b bool) *MetaUpdateOne {
	muo.mutation.SetHidden(b)
	return muo
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableHidden(b *bool) *MetaUpdateOne {
	if b != nil {
		muo.SetHidden(*b)
	}
	return muo
}

// SetContainerType sets the "container_type" field.
func (muo *MetaUpdateOne) SetContainerType(mt meta.ContainerType) *MetaUpdateOne {
	muo.mutation.SetContainerType(mt)
	return muo
}

// SetNillableContainerType sets the "container_type" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableContainerType(mt *meta.ContainerType) *MetaUpdateOne {
	if mt != nil {
		muo.SetContainerType(*mt)
	}
	return muo
}

// SetThumbnailIndex sets the "thumbnail_index" field.
func (muo *MetaUpdateOne) SetThumbnailIndex(i int) *MetaUpdateOne {
	muo.mutation.ResetThumbnailIndex()
	muo.mutation.SetThumbnailIndex(i)
	return muo
}

// SetNillableThumbnailIndex sets the "thumbnail_index" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableThumbnailIndex(i *int) *MetaUpdateOne {
	if i != nil {
		muo.SetThumbnailIndex(*i)
	}
	return muo
}

// AddThumbnailIndex adds i to the "thumbnail_index" field.
func (muo *MetaUpdateOne) AddThumbnailIndex(i int) *MetaUpdateOne {
	muo.mutation.AddThumbnailIndex(i)
	return muo
}

// ClearThumbnailIndex clears the value of the "thumbnail_index" field.
func (muo *MetaUpdateOne) ClearThumbnailIndex() *MetaUpdateOne {
	muo.mutation.ClearThumbnailIndex()
	return muo
}

// SetThumbnailX sets the "thumbnail_x" field.
func (muo *MetaUpdateOne) SetThumbnailX(i int) *MetaUpdateOne {
	muo.mutation.ResetThumbnailX()
	muo.mutation.SetThumbnailX(i)
	return muo
}

// SetNillableThumbnailX sets the "thumbnail_x" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableThumbnailX(i *int) *MetaUpdateOne {
	if i != nil {
		muo.SetThumbnailX(*i)
	}
	return muo
}

// AddThumbnailX adds i to the "thumbnail_x" field.
func (muo *MetaUpdateOne) AddThumbnailX(i int) *MetaUpdateOne {
	muo.mutation.AddThumbnailX(i)
	return muo
}

// ClearThumbnailX clears the value of the "thumbnail_x" field.
func (muo *MetaUpdateOne) ClearThumbnailX() *MetaUpdateOne {
	muo.mutation.ClearThumbnailX()
	return muo
}

// SetThumbnailY sets the "thumbnail_y" field.
func (muo *MetaUpdateOne) SetThumbnailY(i int) *MetaUpdateOne {
	muo.mutation.ResetThumbnailY()
	muo.mutation.SetThumbnailY(i)
	return muo
}

// SetNillableThumbnailY sets the "thumbnail_y" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableThumbnailY(i *int) *MetaUpdateOne {
	if i != nil {
		muo.SetThumbnailY(*i)
	}
	return muo
}

// AddThumbnailY adds i to the "thumbnail_y" field.
func (muo *MetaUpdateOne) AddThumbnailY(i int) *MetaUpdateOne {
	muo.mutation.AddThumbnailY(i)
	return muo
}

// ClearThumbnailY clears the value of the "thumbnail_y" field.
func (muo *MetaUpdateOne) ClearThumbnailY() *MetaUpdateOne {
	muo.mutation.ClearThumbnailY()
	return muo
}

// SetThumbnailWidth sets the "thumbnail_width" field.
func (muo *MetaUpdateOne) SetThumbnailWidth(i int) *MetaUpdateOne {
	muo.mutation.ResetThumbnailWidth()
	muo.mutation.SetThumbnailWidth(i)
	return muo
}

// SetNillableThumbnailWidth sets the "thumbnail_width" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableThumbnailWidth(i *int) *MetaUpdateOne {
	if i != nil {
		muo.SetThumbnailWidth(*i)
	}
	return muo
}

// AddThumbnailWidth adds i to the "thumbnail_width" field.
func (muo *MetaUpdateOne) AddThumbnailWidth(i int) *MetaUpdateOne {
	muo.mutation.AddThumbnailWidth(i)
	return muo
}

// ClearThumbnailWidth clears the value of the "thumbnail_width" field.
func (muo *MetaUpdateOne) ClearThumbnailWidth() *MetaUpdateOne {
	muo.mutation.ClearThumbnailWidth()
	return muo
}

// SetThumbnailHeight sets the "thumbnail_height" field.
func (muo *MetaUpdateOne) SetThumbnailHeight(i int) *MetaUpdateOne {
	muo.mutation.ResetThumbnailHeight()
	muo.mutation.SetThumbnailHeight(i)
	return muo
}

// SetNillableThumbnailHeight sets the "thumbnail_height" field if the given value is not nil.
func (muo *MetaUpdateOne) SetNillableThumbnailHeight(i *int) *MetaUpdateOne {
	if i != nil {
		muo.SetThumbnailHeight(*i)
	}
	return muo
}

// AddThumbnailHeight adds i to the "thumbnail_height" field.
func (muo *MetaUpdateOne) AddThumbnailHeight(i int) *MetaUpdateOne {
	muo.mutation.AddThumbnailHeight(i)
	return muo
}

// ClearThumbnailHeight clears the value of the "thumbnail_height" field.
func (muo *MetaUpdateOne) ClearThumbnailHeight() *MetaUpdateOne {
	muo.mutation.ClearThumbnailHeight()
	return muo
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (muo *MetaUpdateOne) AddTagIDs(ids ...int) *MetaUpdateOne {
	muo.mutation.AddTagIDs(ids...)
	return muo
}

// AddTags adds the "tags" edges to the Tag entity.
func (muo *MetaUpdateOne) AddTags(t ...*Tag) *MetaUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return muo.AddTagIDs(ids...)
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (muo *MetaUpdateOne) AddHistoryIDs(ids ...int) *MetaUpdateOne {
	muo.mutation.AddHistoryIDs(ids...)
	return muo
}

// AddHistories adds the "histories" edges to the History entity.
func (muo *MetaUpdateOne) AddHistories(h ...*History) *MetaUpdateOne {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return muo.AddHistoryIDs(ids...)
}

// AddFavoriteOfUserIDs adds the "favorite_of_user" edge to the User entity by IDs.
func (muo *MetaUpdateOne) AddFavoriteOfUserIDs(ids ...int) *MetaUpdateOne {
	muo.mutation.AddFavoriteOfUserIDs(ids...)
	return muo
}

// AddFavoriteOfUser adds the "favorite_of_user" edges to the User entity.
func (muo *MetaUpdateOne) AddFavoriteOfUser(u ...*User) *MetaUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return muo.AddFavoriteOfUserIDs(ids...)
}

// AddProgresIDs adds the "progress" edge to the Progress entity by IDs.
func (muo *MetaUpdateOne) AddProgresIDs(ids ...int) *MetaUpdateOne {
	muo.mutation.AddProgresIDs(ids...)
	return muo
}

// AddProgress adds the "progress" edges to the Progress entity.
func (muo *MetaUpdateOne) AddProgress(p ...*Progress) *MetaUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return muo.AddProgresIDs(ids...)
}

// Mutation returns the MetaMutation object of the builder.
func (muo *MetaUpdateOne) Mutation() *MetaMutation {
	return muo.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (muo *MetaUpdateOne) ClearTags() *MetaUpdateOne {
	muo.mutation.ClearTags()
	return muo
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (muo *MetaUpdateOne) RemoveTagIDs(ids ...int) *MetaUpdateOne {
	muo.mutation.RemoveTagIDs(ids...)
	return muo
}

// RemoveTags removes "tags" edges to Tag entities.
func (muo *MetaUpdateOne) RemoveTags(t ...*Tag) *MetaUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return muo.RemoveTagIDs(ids...)
}

// ClearHistories clears all "histories" edges to the History entity.
func (muo *MetaUpdateOne) ClearHistories() *MetaUpdateOne {
	muo.mutation.ClearHistories()
	return muo
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (muo *MetaUpdateOne) RemoveHistoryIDs(ids ...int) *MetaUpdateOne {
	muo.mutation.RemoveHistoryIDs(ids...)
	return muo
}

// RemoveHistories removes "histories" edges to History entities.
func (muo *MetaUpdateOne) RemoveHistories(h ...*History) *MetaUpdateOne {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return muo.RemoveHistoryIDs(ids...)
}

// ClearFavoriteOfUser clears all "favorite_of_user" edges to the User entity.
func (muo *MetaUpdateOne) ClearFavoriteOfUser() *MetaUpdateOne {
	muo.mutation.ClearFavoriteOfUser()
	return muo
}

// RemoveFavoriteOfUserIDs removes the "favorite_of_user" edge to User entities by IDs.
func (muo *MetaUpdateOne) RemoveFavoriteOfUserIDs(ids ...int) *MetaUpdateOne {
	muo.mutation.RemoveFavoriteOfUserIDs(ids...)
	return muo
}

// RemoveFavoriteOfUser removes "favorite_of_user" edges to User entities.
func (muo *MetaUpdateOne) RemoveFavoriteOfUser(u ...*User) *MetaUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return muo.RemoveFavoriteOfUserIDs(ids...)
}

// ClearProgress clears all "progress" edges to the Progress entity.
func (muo *MetaUpdateOne) ClearProgress() *MetaUpdateOne {
	muo.mutation.ClearProgress()
	return muo
}

// RemoveProgresIDs removes the "progress" edge to Progress entities by IDs.
func (muo *MetaUpdateOne) RemoveProgresIDs(ids ...int) *MetaUpdateOne {
	muo.mutation.RemoveProgresIDs(ids...)
	return muo
}

// RemoveProgress removes "progress" edges to Progress entities.
func (muo *MetaUpdateOne) RemoveProgress(p ...*Progress) *MetaUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return muo.RemoveProgresIDs(ids...)
}

// Where appends a list predicates to the MetaUpdate builder.
func (muo *MetaUpdateOne) Where(ps ...predicate.Meta) *MetaUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MetaUpdateOne) Select(field string, fields ...string) *MetaUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Meta entity.
func (muo *MetaUpdateOne) Save(ctx context.Context) (*Meta, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MetaUpdateOne) SaveX(ctx context.Context) *Meta {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MetaUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MetaUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MetaUpdateOne) check() error {
	if v, ok := muo.mutation.Name(); ok {
		if err := meta.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Meta.name": %w`, err)}
		}
	}
	if v, ok := muo.mutation.ContainerType(); ok {
		if err := meta.ContainerTypeValidator(v); err != nil {
			return &ValidationError{Name: "container_type", err: fmt.Errorf(`ent: validator failed for field "Meta.container_type": %w`, err)}
		}
	}
	return nil
}

func (muo *MetaUpdateOne) sqlSave(ctx context.Context) (_node *Meta, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(meta.Table, meta.Columns, sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Meta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meta.FieldID)
		for _, f := range fields {
			if !meta.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != meta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Name(); ok {
		_spec.SetField(meta.FieldName, field.TypeString, value)
	}
	if value, ok := muo.mutation.CreateTime(); ok {
		_spec.SetField(meta.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := muo.mutation.Favorite(); ok {
		_spec.SetField(meta.FieldFavorite, field.TypeBool, value)
	}
	if value, ok := muo.mutation.FileIndices(); ok {
		_spec.SetField(meta.FieldFileIndices, field.TypeJSON, value)
	}
	if value, ok := muo.mutation.AppendedFileIndices(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, meta.FieldFileIndices, value)
		})
	}
	if value, ok := muo.mutation.Read(); ok {
		_spec.SetField(meta.FieldRead, field.TypeBool, value)
	}
	if value, ok := muo.mutation.Active(); ok {
		_spec.SetField(meta.FieldActive, field.TypeBool, value)
	}
	if value, ok := muo.mutation.Hidden(); ok {
		_spec.SetField(meta.FieldHidden, field.TypeBool, value)
	}
	if value, ok := muo.mutation.ContainerType(); ok {
		_spec.SetField(meta.FieldContainerType, field.TypeEnum, value)
	}
	if value, ok := muo.mutation.ThumbnailIndex(); ok {
		_spec.SetField(meta.FieldThumbnailIndex, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedThumbnailIndex(); ok {
		_spec.AddField(meta.FieldThumbnailIndex, field.TypeInt, value)
	}
	if muo.mutation.ThumbnailIndexCleared() {
		_spec.ClearField(meta.FieldThumbnailIndex, field.TypeInt)
	}
	if value, ok := muo.mutation.ThumbnailX(); ok {
		_spec.SetField(meta.FieldThumbnailX, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedThumbnailX(); ok {
		_spec.AddField(meta.FieldThumbnailX, field.TypeInt, value)
	}
	if muo.mutation.ThumbnailXCleared() {
		_spec.ClearField(meta.FieldThumbnailX, field.TypeInt)
	}
	if value, ok := muo.mutation.ThumbnailY(); ok {
		_spec.SetField(meta.FieldThumbnailY, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedThumbnailY(); ok {
		_spec.AddField(meta.FieldThumbnailY, field.TypeInt, value)
	}
	if muo.mutation.ThumbnailYCleared() {
		_spec.ClearField(meta.FieldThumbnailY, field.TypeInt)
	}
	if value, ok := muo.mutation.ThumbnailWidth(); ok {
		_spec.SetField(meta.FieldThumbnailWidth, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedThumbnailWidth(); ok {
		_spec.AddField(meta.FieldThumbnailWidth, field.TypeInt, value)
	}
	if muo.mutation.ThumbnailWidthCleared() {
		_spec.ClearField(meta.FieldThumbnailWidth, field.TypeInt)
	}
	if value, ok := muo.mutation.ThumbnailHeight(); ok {
		_spec.SetField(meta.FieldThumbnailHeight, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedThumbnailHeight(); ok {
		_spec.AddField(meta.FieldThumbnailHeight, field.TypeInt, value)
	}
	if muo.mutation.ThumbnailHeightCleared() {
		_spec.ClearField(meta.FieldThumbnailHeight, field.TypeInt)
	}
	if muo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedTagsIDs(); len(nodes) > 0 && !muo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !muo.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedFavoriteOfUserIDs(); len(nodes) > 0 && !muo.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.FavoriteOfUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedProgressIDs(); len(nodes) > 0 && !muo.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Meta{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{meta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
