// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: service/v1/meta.proto

package v1

import (
	entpb "github.com/wutipong/mangaweb3-backend/ent/proto/entpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of ent/proto/entpb/entpb.proto.

type Meta = entpb.Meta
type Tag = entpb.Tag

type SORT_BY int32

const (
	SORT_BY_SORT_BY_CREATE_TIME SORT_BY = 0
	SORT_BY_SORT_BY_NAME        SORT_BY = 1
)

// Enum value maps for SORT_BY.
var (
	SORT_BY_name = map[int32]string{
		0: "SORT_BY_CREATE_TIME",
		1: "SORT_BY_NAME",
	}
	SORT_BY_value = map[string]int32{
		"SORT_BY_CREATE_TIME": 0,
		"SORT_BY_NAME":        1,
	}
)

func (x SORT_BY) Enum() *SORT_BY {
	p := new(SORT_BY)
	*p = x
	return p
}

func (x SORT_BY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SORT_BY) Descriptor() protoreflect.EnumDescriptor {
	return file_service_v1_meta_proto_enumTypes[0].Descriptor()
}

func (SORT_BY) Type() protoreflect.EnumType {
	return &file_service_v1_meta_proto_enumTypes[0]
}

func (x SORT_BY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SORT_BY.Descriptor instead.
func (SORT_BY) EnumDescriptor() ([]byte, []int) {
	return file_service_v1_meta_proto_rawDescGZIP(), []int{0}
}

type ORDER int32

const (
	ORDER_ORDER_ASCENDING  ORDER = 0
	ORDER_ORDER_DESCENDING ORDER = 1
)

// Enum value maps for ORDER.
var (
	ORDER_name = map[int32]string{
		0: "ORDER_ASCENDING",
		1: "ORDER_DESCENDING",
	}
	ORDER_value = map[string]int32{
		"ORDER_ASCENDING":  0,
		"ORDER_DESCENDING": 1,
	}
)

func (x ORDER) Enum() *ORDER {
	p := new(ORDER)
	*p = x
	return p
}

func (x ORDER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ORDER) Descriptor() protoreflect.EnumDescriptor {
	return file_service_v1_meta_proto_enumTypes[1].Descriptor()
}

func (ORDER) Type() protoreflect.EnumType {
	return &file_service_v1_meta_proto_enumTypes[1]
}

func (x ORDER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ORDER.Descriptor instead.
func (ORDER) EnumDescriptor() ([]byte, []int) {
	return file_service_v1_meta_proto_rawDescGZIP(), []int{1}
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag          string  `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	FavoriteOnly bool    `protobuf:"varint,2,opt,name=FavoriteOnly,proto3" json:"FavoriteOnly,omitempty"`
	Page         int32   `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	ItemPerPage  int32   `protobuf:"varint,4,opt,name=ItemPerPage,proto3" json:"ItemPerPage,omitempty"`
	Search       string  `protobuf:"bytes,5,opt,name=Search,proto3" json:"Search,omitempty"`
	Sort         SORT_BY `protobuf:"varint,6,opt,name=Sort,proto3,enum=SORT_BY" json:"Sort,omitempty"`
	Order        ORDER   `protobuf:"varint,7,opt,name=Order,proto3,enum=ORDER" json:"Order,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListRequest) GetFavoriteOnly() bool {
	if x != nil {
		return x.FavoriteOnly
	}
	return false
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetItemPerPage() int32 {
	if x != nil {
		return x.ItemPerPage
	}
	return 0
}

func (x *ListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListRequest) GetSort() SORT_BY {
	if x != nil {
		return x.Sort
	}
	return SORT_BY_SORT_BY_CREATE_TIME
}

func (x *ListRequest) GetOrder() ORDER {
	if x != nil {
		return x.Order
	}
	return ORDER_ORDER_ASCENDING
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagFavorite bool        `protobuf:"varint,1,opt,name=TagFavorite,proto3" json:"TagFavorite,omitempty"`
	TotalPage   int32       `protobuf:"varint,2,opt,name=TotalPage,proto3" json:"TotalPage,omitempty"`
	Items       *entpb.Meta `protobuf:"bytes,3,opt,name=Items,proto3" json:"Items,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetTagFavorite() bool {
	if x != nil {
		return x.TagFavorite
	}
	return false
}

func (x *ListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *ListResponse) GetItems() *entpb.Meta {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_meta_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item      *entpb.Meta  `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item,omitempty"`
	PageCount int32        `protobuf:"varint,2,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	Tags      []*entpb.Tag `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_meta_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetItem() *entpb.Meta {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetResponse) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *GetResponse) GetTags() []*entpb.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_service_v1_meta_proto protoreflect.FileDescriptor

var file_service_v1_meta_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x46, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1c, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59,
	0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x52, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x71, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x61, 0x67, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x54, 0x61, 0x67, 0x46, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x1c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x54,
	0x61, 0x67, 0x73, 0x2a, 0x34, 0x0a, 0x07, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x12, 0x17,
	0x0a, 0x13, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x42, 0x59, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x4f, 0x52, 0x54, 0x5f,
	0x42, 0x59, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x01, 0x2a, 0x32, 0x0a, 0x05, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x41, 0x53, 0x43, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x5f, 0x44, 0x45, 0x53, 0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x32, 0x51, 0x0a,
	0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0c, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x0b, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x50, 0x00,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_v1_meta_proto_rawDescOnce sync.Once
	file_service_v1_meta_proto_rawDescData = file_service_v1_meta_proto_rawDesc
)

func file_service_v1_meta_proto_rawDescGZIP() []byte {
	file_service_v1_meta_proto_rawDescOnce.Do(func() {
		file_service_v1_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_v1_meta_proto_rawDescData)
	})
	return file_service_v1_meta_proto_rawDescData
}

var file_service_v1_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_v1_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_v1_meta_proto_goTypes = []interface{}{
	(SORT_BY)(0),         // 0: SORT_BY
	(ORDER)(0),           // 1: ORDER
	(*ListRequest)(nil),  // 2: ListRequest
	(*ListResponse)(nil), // 3: ListResponse
	(*GetRequest)(nil),   // 4: GetRequest
	(*GetResponse)(nil),  // 5: GetResponse
	(*entpb.Meta)(nil),   // 6: entpb.Meta
	(*entpb.Tag)(nil),    // 7: entpb.Tag
}
var file_service_v1_meta_proto_depIdxs = []int32{
	0, // 0: ListRequest.Sort:type_name -> SORT_BY
	1, // 1: ListRequest.Order:type_name -> ORDER
	6, // 2: ListResponse.Items:type_name -> entpb.Meta
	6, // 3: GetResponse.Item:type_name -> entpb.Meta
	7, // 4: GetResponse.Tags:type_name -> entpb.Tag
	2, // 5: Meta.List:input_type -> ListRequest
	4, // 6: Meta.Get:input_type -> GetRequest
	3, // 7: Meta.List:output_type -> ListResponse
	5, // 8: Meta.Get:output_type -> GetResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_service_v1_meta_proto_init() }
func file_service_v1_meta_proto_init() {
	if File_service_v1_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_v1_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_v1_meta_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_meta_proto_goTypes,
		DependencyIndexes: file_service_v1_meta_proto_depIdxs,
		EnumInfos:         file_service_v1_meta_proto_enumTypes,
		MessageInfos:      file_service_v1_meta_proto_msgTypes,
	}.Build()
	File_service_v1_meta_proto = out.File
	file_service_v1_meta_proto_rawDesc = nil
	file_service_v1_meta_proto_goTypes = nil
	file_service_v1_meta_proto_depIdxs = nil
}
