// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Meta is the predicate function for meta builders.
type Meta func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
